### ISSUE TITLE
Jail Console Error

### ISSUE THREAD

**Issue by LucidAPs** [Zrips/CMI-API#21]
Console error when trying to jail some users
https://nekobin.com/rumazesuga

**Comment by mrfloris** [comment]
Due to lack of replying by zrips (judging eyes, sorry) the pastebin has expired now, however, the website zrips.net > cmi > API page now has info about the jail events, and cmi is on 9.3 and cmi API is now supporting 9.3 better. If this is still in need of a solution you can update everything and try again. Feel free to open a new ticket if it's not resolved for you.
